### ISSUE TITLE
upgrade from `RDFS2020` style to `RDFSEd2Beta` style

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/Inst4CIM-KG#41]
NC 2.3 uses the older `RDFS2020` style, CGMES 3.0 uses the new `RDFSEd2Beta` style.
Upgrading to `RDFSEd2Beta` will harmonize data and simplify SPARQL Updates.
@Sveino Is there a formal spec for `RDFSEd2Beta`? I've seen an "RDF usage guide", please link it

@Sveino and @griddigit-ci, let's list all differences:
- [x] New `cim` and `eu` namespaces: can be seen in https://github.com/Sveino/Inst4CIM-KG/issues/13, https://github.com/Sveino/Inst4CIM-KG/issues/68
- [x] `rdfs:Class -> owl:Class`: https://github.com/Sveino/Inst4CIM-KG/issues/75
- [x] `rdf:Property -> owl:ObjectProperty, owl:DatatypeProperty`: https://github.com/Sveino/Inst4CIM-KG/issues/75
- [x] `cims:dataType cim:String -> rdfs:range xsd:string` etc: https://github.com/Sveino/Inst4CIM-KG/issues/28, https://github.com/Sveino/Inst4CIM-KG/issues/61
- [x] Delete CIM Primitive datatypes https://github.com/Sveino/Inst4CIM-KG/issues/74
- [x] `cims:inverseRoleName -> owl:inverseOf`: https://github.com/Sveino/Inst4CIM-KG/issues/26
- [x] `cims:multiplicity cims:M:*..1 -> owl:FunctionalProperty`: https://github.com/Sveino/Inst4CIM-KG/issues/30.
  - But it's better to also keep `cims:multiplicity`. It's reflected in SHACL but keeping it gives easier access to this important info
  - Declare the **inverse** relationas `owl:InverseFunctionalProperty`
- [ ] Bring all meta-props back to `cims:` namespace (this is a regression): https://github.com/Sveino/Inst4CIM-KG/issues/10. 
  - https://github.com/Sveino/Inst4CIM-KG/issues/4 is also related
- [ ] Fix enumerations (this is not a difference, but still nice to fix): https://github.com/Sveino/Inst4CIM-KG/issues/7, https://github.com/Sveino/Inst4CIM-KG/issues/11
- [ ] Fix enumeration members (this is a regression) https://github.com/Sveino/Inst4CIM-KG/issues/45
- [ ] Fix packages (this is not a difference, but still nice to fix):  https://github.com/Sveino/Inst4CIM-KG/issues/12
- [x] Multipliers and Units (attached to QuantityKinds) are styled differently, see section `## Actual Multipliers and Units`. Affects https://github.com/Sveino/Inst4CIM-KG/issues/38
- [ ] `rdfs:comment -> skos:definition` for individuals (eg `cim:UnitSymbol.W a owl:NamedIndividual`)

**Comment by VladimirAlexiev** [comment]
- SPARQL fixes should be implemented only for the 2020 style
- https://github.com/Sveino/Spec4CIM-KG/blob/develop/docs/Profile/UML2RDF.md is the spec for UML conversion, which also lists the differences. (Note: the link is private, and the markdown is converted from docx, so it's not yet perfect).
@Sveino and @griddigit-ci do you have more tasks (checkboxes) to add?
